// GENERATED CODE -- DO NOT EDIT!
// Generated by generate-server-setup.mjs
import * as grpc from "@grpc/grpc-js"
import * as proto from "@/shared/proto"
import { Controller } from "../core/controller"
import { GrpcHandlerWrapper, GrpcStreamingResponseHandlerWrapper } from "./grpc-types"

// Account Service
import { accountLoginClicked } from "../core/controller/account/accountLoginClicked"
import { accountLogoutClicked } from "../core/controller/account/accountLogoutClicked"
import { subscribeToAuthCallback } from "../core/controller/account/subscribeToAuthCallback"
import { authStateChanged } from "../core/controller/account/authStateChanged"
import { fetchUserCreditsData } from "../core/controller/account/fetchUserCreditsData"

// Browser Service
import { getBrowserConnectionInfo } from "../core/controller/browser/getBrowserConnectionInfo"
import { testBrowserConnection } from "../core/controller/browser/testBrowserConnection"
import { discoverBrowser } from "../core/controller/browser/discoverBrowser"
import { getDetectedChromePath } from "../core/controller/browser/getDetectedChromePath"
import { updateBrowserSettings } from "../core/controller/browser/updateBrowserSettings"
import { relaunchChromeDebugMode } from "../core/controller/browser/relaunchChromeDebugMode"

// Checkpoints Service
import { checkpointDiff } from "../core/controller/checkpoints/checkpointDiff"
import { checkpointRestore } from "../core/controller/checkpoints/checkpointRestore"

// File Service
import { copyToClipboard } from "../core/controller/file/copyToClipboard"
import { openFile } from "../core/controller/file/openFile"
import { openImage } from "../core/controller/file/openImage"
import { openMention } from "../core/controller/file/openMention"
import { deleteRuleFile } from "../core/controller/file/deleteRuleFile"
import { createRuleFile } from "../core/controller/file/createRuleFile"
import { searchCommits } from "../core/controller/file/searchCommits"
import { selectImages } from "../core/controller/file/selectImages"
import { selectFiles } from "../core/controller/file/selectFiles"
import { getRelativePaths } from "../core/controller/file/getRelativePaths"
import { searchFiles } from "../core/controller/file/searchFiles"
import { toggleClineRule } from "../core/controller/file/toggleClineRule"
import { toggleCursorRule } from "../core/controller/file/toggleCursorRule"
import { toggleWindsurfRule } from "../core/controller/file/toggleWindsurfRule"
import { refreshRules } from "../core/controller/file/refreshRules"
import { openTaskHistory } from "../core/controller/file/openTaskHistory"
import { toggleWorkflow } from "../core/controller/file/toggleWorkflow"
import { subscribeToWorkspaceUpdates } from "../core/controller/file/subscribeToWorkspaceUpdates"

// Mcp Service
import { toggleMcpServer } from "../core/controller/mcp/toggleMcpServer"
import { updateMcpTimeout } from "../core/controller/mcp/updateMcpTimeout"
import { addRemoteMcpServer } from "../core/controller/mcp/addRemoteMcpServer"
import { downloadMcp } from "../core/controller/mcp/downloadMcp"
import { restartMcpServer } from "../core/controller/mcp/restartMcpServer"
import { deleteMcpServer } from "../core/controller/mcp/deleteMcpServer"
import { toggleToolAutoApprove } from "../core/controller/mcp/toggleToolAutoApprove"
import { refreshMcpMarketplace } from "../core/controller/mcp/refreshMcpMarketplace"
import { openMcpSettings } from "../core/controller/mcp/openMcpSettings"
import { subscribeToMcpMarketplaceCatalog } from "../core/controller/mcp/subscribeToMcpMarketplaceCatalog"
import { getLatestMcpServers } from "../core/controller/mcp/getLatestMcpServers"
import { subscribeToMcpServers } from "../core/controller/mcp/subscribeToMcpServers"

// Models Service
import { getOllamaModels } from "../core/controller/models/getOllamaModels"
import { getLmStudioModels } from "../core/controller/models/getLmStudioModels"
import { getVsCodeLmModels } from "../core/controller/models/getVsCodeLmModels"
import { refreshOpenRouterModels } from "../core/controller/models/refreshOpenRouterModels"
import { refreshOpenAiModels } from "../core/controller/models/refreshOpenAiModels"
import { refreshRequestyModels } from "../core/controller/models/refreshRequestyModels"
import { refreshShengSuanYunModels } from "../core/controller/models/refreshShengSuanYunModels"
import { subscribeToOpenRouterModels } from "../core/controller/models/subscribeToOpenRouterModels"

// Slash Service
import { reportBug } from "../core/controller/slash/reportBug"
import { condense } from "../core/controller/slash/condense"

// State Service
import { getLatestState } from "../core/controller/state/getLatestState"
import { subscribeToState } from "../core/controller/state/subscribeToState"
import { toggleFavoriteModel } from "../core/controller/state/toggleFavoriteModel"
import { resetState } from "../core/controller/state/resetState"
import { togglePlanActMode } from "../core/controller/state/togglePlanActMode"
import { updateTerminalConnectionTimeout } from "../core/controller/state/updateTerminalConnectionTimeout"
import { updateAutoApprovalSettings } from "../core/controller/state/updateAutoApprovalSettings"
import { updateSettings } from "../core/controller/state/updateSettings"

// Task Service
import { cancelTask } from "../core/controller/task/cancelTask"
import { clearTask } from "../core/controller/task/clearTask"
import { getTotalTasksSize } from "../core/controller/task/getTotalTasksSize"
import { deleteTasksWithIds } from "../core/controller/task/deleteTasksWithIds"
import { newTask } from "../core/controller/task/newTask"
import { showTaskWithId } from "../core/controller/task/showTaskWithId"
import { exportTaskWithId } from "../core/controller/task/exportTaskWithId"
import { toggleTaskFavorite } from "../core/controller/task/toggleTaskFavorite"
import { deleteNonFavoritedTasks } from "../core/controller/task/deleteNonFavoritedTasks"
import { getTaskHistory } from "../core/controller/task/getTaskHistory"
import { askResponse } from "../core/controller/task/askResponse"
import { taskFeedback } from "../core/controller/task/taskFeedback"
import { taskCompletionViewChanges } from "../core/controller/task/taskCompletionViewChanges"
import { executeQuickWin } from "../core/controller/task/executeQuickWin"

// Ui Service
import { scrollToSettings } from "../core/controller/ui/scrollToSettings"
import { onDidShowAnnouncement } from "../core/controller/ui/onDidShowAnnouncement"
import { subscribeToAddToInput } from "../core/controller/ui/subscribeToAddToInput"
import { subscribeToMcpButtonClicked } from "../core/controller/ui/subscribeToMcpButtonClicked"
import { subscribeToHistoryButtonClicked } from "../core/controller/ui/subscribeToHistoryButtonClicked"
import { subscribeToChatButtonClicked } from "../core/controller/ui/subscribeToChatButtonClicked"
import { subscribeToAccountButtonClicked } from "../core/controller/ui/subscribeToAccountButtonClicked"
import { subscribeToSettingsButtonClicked } from "../core/controller/ui/subscribeToSettingsButtonClicked"
import { subscribeToPartialMessage } from "../core/controller/ui/subscribeToPartialMessage"
import { subscribeToTheme } from "../core/controller/ui/subscribeToTheme"
import { initializeWebview } from "../core/controller/ui/initializeWebview"
import { subscribeToRelinquishControl } from "../core/controller/ui/subscribeToRelinquishControl"

// Web Service
import { checkIsImageUrl } from "../core/controller/web/checkIsImageUrl"
import { fetchOpenGraphData } from "../core/controller/web/fetchOpenGraphData"
import { openInBrowser } from "../core/controller/web/openInBrowser"

export function addServices(
	server: grpc.Server,
	proto: any,
	controller: Controller,
	wrapper: GrpcHandlerWrapper,
	wrapStreamingResponse: GrpcStreamingResponseHandlerWrapper,
): void {
    // Account Service
    server.addService(proto.clineChinese.AccountService.service, {
         accountLoginClicked: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.String>(accountLoginClicked, controller),
         accountLogoutClicked: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.Empty>(accountLogoutClicked, controller),
        subscribeToAuthCallback: wrapStreamingResponse<proto.clineChinese.EmptyRequest,void>(subscribeToAuthCallback, controller),
         authStateChanged: wrapper<proto.clineChinese.AuthStateChangedRequest,proto.clineChinese.AuthStateChanged>(authStateChanged, controller),
         fetchUserCreditsData: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.UserCreditsData>(fetchUserCreditsData, controller),
    });

    // Browser Service
    server.addService(proto.clineChinese.BrowserService.service, {
         getBrowserConnectionInfo: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.BrowserConnectionInfo>(getBrowserConnectionInfo, controller),
         testBrowserConnection: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.BrowserConnection>(testBrowserConnection, controller),
         discoverBrowser: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.BrowserConnection>(discoverBrowser, controller),
         getDetectedChromePath: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.ChromePath>(getDetectedChromePath, controller),
         updateBrowserSettings: wrapper<proto.clineChinese.UpdateBrowserSettingsRequest,proto.clineChinese.Boolean>(updateBrowserSettings, controller),
         relaunchChromeDebugMode: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.String>(relaunchChromeDebugMode, controller),
    });

    // Checkpoints Service
    server.addService(proto.clineChinese.CheckpointsService.service, {
         checkpointDiff: wrapper<proto.clineChinese.Int64Request,proto.clineChinese.Empty>(checkpointDiff, controller),
         checkpointRestore: wrapper<proto.clineChinese.CheckpointRestoreRequest,proto.clineChinese.Empty>(checkpointRestore, controller),
    });

    // File Service
    server.addService(proto.clineChinese.FileService.service, {
         copyToClipboard: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.Empty>(copyToClipboard, controller),
         openFile: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.Empty>(openFile, controller),
         openImage: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.Empty>(openImage, controller),
         openMention: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.Empty>(openMention, controller),
         deleteRuleFile: wrapper<proto.clineChinese.RuleFileRequest,proto.clineChinese.RuleFile>(deleteRuleFile, controller),
         createRuleFile: wrapper<proto.clineChinese.RuleFileRequest,proto.clineChinese.RuleFile>(createRuleFile, controller),
         searchCommits: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.GitCommits>(searchCommits, controller),
         selectImages: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.StringArray>(selectImages, controller),
         selectFiles: wrapper<proto.clineChinese.BooleanRequest,proto.clineChinese.StringArrays>(selectFiles, controller),
         getRelativePaths: wrapper<proto.clineChinese.RelativePathsRequest,proto.clineChinese.RelativePaths>(getRelativePaths, controller),
         searchFiles: wrapper<proto.clineChinese.FileSearchRequest,proto.clineChinese.FileSearchResults>(searchFiles, controller),
         toggleClineRule: wrapper<proto.clineChinese.ToggleClineRuleRequest,proto.clineChinese.ToggleClineRules>(toggleClineRule, controller),
         toggleCursorRule: wrapper<proto.clineChinese.ToggleCursorRuleRequest,proto.clineChinese.ClineRulesToggles>(toggleCursorRule, controller),
         toggleWindsurfRule: wrapper<proto.clineChinese.ToggleWindsurfRuleRequest,proto.clineChinese.ClineRulesToggles>(toggleWindsurfRule, controller),
         refreshRules: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.RefreshedRules>(refreshRules, controller),
         openTaskHistory: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.Empty>(openTaskHistory, controller),
         toggleWorkflow: wrapper<proto.clineChinese.ToggleWorkflowRequest,proto.clineChinese.ClineRulesToggles>(toggleWorkflow, controller),
        subscribeToWorkspaceUpdates: wrapStreamingResponse<proto.clineChinese.EmptyRequest,void>(subscribeToWorkspaceUpdates, controller),
    });

    // Mcp Service
    server.addService(proto.clineChinese.McpService.service, {
         toggleMcpServer: wrapper<proto.clineChinese.ToggleMcpServerRequest,proto.clineChinese.McpServers>(toggleMcpServer, controller),
         updateMcpTimeout: wrapper<proto.clineChinese.UpdateMcpTimeoutRequest,proto.clineChinese.McpServers>(updateMcpTimeout, controller),
         addRemoteMcpServer: wrapper<proto.clineChinese.AddRemoteMcpServerRequest,proto.clineChinese.McpServers>(addRemoteMcpServer, controller),
         downloadMcp: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.Empty>(downloadMcp, controller),
         restartMcpServer: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.McpServers>(restartMcpServer, controller),
         deleteMcpServer: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.McpServers>(deleteMcpServer, controller),
         toggleToolAutoApprove: wrapper<proto.clineChinese.ToggleToolAutoApproveRequest,proto.clineChinese.McpServers>(toggleToolAutoApprove, controller),
         refreshMcpMarketplace: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.McpMarketplaceCatalog>(refreshMcpMarketplace, controller),
         openMcpSettings: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.Empty>(openMcpSettings, controller),
        subscribeToMcpMarketplaceCatalog: wrapStreamingResponse<proto.clineChinese.EmptyRequest,void>(subscribeToMcpMarketplaceCatalog, controller),
         getLatestMcpServers: wrapper<proto.clineChinese.Empty,proto.clineChinese.McpServers>(getLatestMcpServers, controller),
        subscribeToMcpServers: wrapStreamingResponse<proto.clineChinese.EmptyRequest,void>(subscribeToMcpServers, controller),
    });

    // Models Service
    server.addService(proto.clineChinese.ModelsService.service, {
         getOllamaModels: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.StringArray>(getOllamaModels, controller),
         getLmStudioModels: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.StringArray>(getLmStudioModels, controller),
         getVsCodeLmModels: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.VsCodeLmModelsArray>(getVsCodeLmModels, controller),
         refreshOpenRouterModels: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.OpenRouterCompatibleModelInfo>(refreshOpenRouterModels, controller),
         refreshOpenAiModels: wrapper<proto.clineChinese.OpenAiModelsRequest,proto.clineChinese.StringArray>(refreshOpenAiModels, controller),
         refreshRequestyModels: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.OpenRouterCompatibleModelInfo>(refreshRequestyModels, controller),
         refreshShengSuanYunModels: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.OpenRouterCompatibleModelInfo>(refreshShengSuanYunModels, controller),
        subscribeToOpenRouterModels: wrapStreamingResponse<proto.clineChinese.EmptyRequest,void>(subscribeToOpenRouterModels, controller),
    });

    // Slash Service
    server.addService(proto.clineChinese.SlashService.service, {
         reportBug: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.Empty>(reportBug, controller),
         condense: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.Empty>(condense, controller),
    });

    // State Service
    server.addService(proto.clineChinese.StateService.service, {
         getLatestState: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.State>(getLatestState, controller),
        subscribeToState: wrapStreamingResponse<proto.clineChinese.EmptyRequest,void>(subscribeToState, controller),
         toggleFavoriteModel: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.Empty>(toggleFavoriteModel, controller),
         resetState: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.Empty>(resetState, controller),
         togglePlanActMode: wrapper<proto.clineChinese.TogglePlanActModeRequest,proto.clineChinese.Empty>(togglePlanActMode, controller),
         updateTerminalConnectionTimeout: wrapper<proto.clineChinese.Int64Request,proto.clineChinese.Int64>(updateTerminalConnectionTimeout, controller),
         updateAutoApprovalSettings: wrapper<proto.clineChinese.AutoApprovalSettingsRequest,proto.clineChinese.Empty>(updateAutoApprovalSettings, controller),
         updateSettings: wrapper<proto.clineChinese.UpdateSettingsRequest,proto.clineChinese.Empty>(updateSettings, controller),
    });

    // Task Service
    server.addService(proto.clineChinese.TaskService.service, {
         cancelTask: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.Empty>(cancelTask, controller),
         clearTask: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.Empty>(clearTask, controller),
         getTotalTasksSize: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.Int64>(getTotalTasksSize, controller),
         deleteTasksWithIds: wrapper<proto.clineChinese.StringArrayRequest,proto.clineChinese.Empty>(deleteTasksWithIds, controller),
         newTask: wrapper<proto.clineChinese.NewTaskRequest,proto.clineChinese.Empty>(newTask, controller),
         showTaskWithId: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.TaskResponse>(showTaskWithId, controller),
         exportTaskWithId: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.Empty>(exportTaskWithId, controller),
         toggleTaskFavorite: wrapper<proto.clineChinese.TaskFavoriteRequest,proto.clineChinese.Empty>(toggleTaskFavorite, controller),
         deleteNonFavoritedTasks: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.DeleteNonFavoritedTasksResults>(deleteNonFavoritedTasks, controller),
         getTaskHistory: wrapper<proto.clineChinese.GetTaskHistoryRequest,proto.clineChinese.TaskHistoryArray>(getTaskHistory, controller),
         askResponse: wrapper<proto.clineChinese.AskResponseRequest,proto.clineChinese.Empty>(askResponse, controller),
         taskFeedback: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.Empty>(taskFeedback, controller),
         taskCompletionViewChanges: wrapper<proto.clineChinese.Int64Request,proto.clineChinese.Empty>(taskCompletionViewChanges, controller),
         executeQuickWin: wrapper<proto.clineChinese.ExecuteQuickWinRequest,proto.clineChinese.Empty>(executeQuickWin, controller),
    });

    // Ui Service
    server.addService(proto.clineChinese.UiService.service, {
         scrollToSettings: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.KeyValuePair>(scrollToSettings, controller),
         onDidShowAnnouncement: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.Boolean>(onDidShowAnnouncement, controller),
        subscribeToAddToInput: wrapStreamingResponse<proto.clineChinese.EmptyRequest,void>(subscribeToAddToInput, controller),
        subscribeToMcpButtonClicked: wrapStreamingResponse<proto.clineChinese.WebviewProviderTypeRequest,void>(subscribeToMcpButtonClicked, controller),
        subscribeToHistoryButtonClicked: wrapStreamingResponse<proto.clineChinese.WebviewProviderTypeRequest,void>(subscribeToHistoryButtonClicked, controller),
        subscribeToChatButtonClicked: wrapStreamingResponse<proto.clineChinese.EmptyRequest,void>(subscribeToChatButtonClicked, controller),
        subscribeToAccountButtonClicked: wrapStreamingResponse<proto.clineChinese.EmptyRequest,void>(subscribeToAccountButtonClicked, controller),
        subscribeToSettingsButtonClicked: wrapStreamingResponse<proto.clineChinese.WebviewProviderTypeRequest,void>(subscribeToSettingsButtonClicked, controller),
        subscribeToPartialMessage: wrapStreamingResponse<proto.clineChinese.EmptyRequest,void>(subscribeToPartialMessage, controller),
        subscribeToTheme: wrapStreamingResponse<proto.clineChinese.EmptyRequest,void>(subscribeToTheme, controller),
         initializeWebview: wrapper<proto.clineChinese.EmptyRequest,proto.clineChinese.Empty>(initializeWebview, controller),
        subscribeToRelinquishControl: wrapStreamingResponse<proto.clineChinese.EmptyRequest,void>(subscribeToRelinquishControl, controller),
    });

    // Web Service
    server.addService(proto.clineChinese.WebService.service, {
         checkIsImageUrl: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.IsImageUrl>(checkIsImageUrl, controller),
         fetchOpenGraphData: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.OpenGraphData>(fetchOpenGraphData, controller),
         openInBrowser: wrapper<proto.clineChinese.StringRequest,proto.clineChinese.Empty>(openInBrowser, controller),
    });

}
